# Generated by Django 4.1.6 on 2023-02-10 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='country_code',
            field=models.CharField(default='91', max_length=2),
        ),
    ]
