# Generated by Django 4.1.6 on 2023-02-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='message',
            field=models.CharField(default='amazone', max_length=260),
            preserve_default=False,
        ),
    ]
