# Generated by Django 4.1.7 on 2023-02-22 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_otp_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Otp',
        ),
    ]
