# Generated by Django 4.1.6 on 2023-02-13 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=120)),
                ('package_name', models.CharField(max_length=260, unique=True)),
                ('label', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('label', models.CharField(default='family', max_length=120)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_duration', models.CharField(choices=[('2h', '2 hours'), ('to', 'today'), ('tm', 'tomarrow'), ('al', 'always')], default='2h', max_length=2)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('last_update', models.DateField(auto_now_add=True)),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='member.contact')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
                ('selected_apps', models.ManyToManyField(to='member.app')),
            ],
        ),
    ]
