# Generated by Django 4.1.6 on 2023-02-14 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='contact',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='member.contact'),
        ),
        migrations.AlterField(
            model_name='config',
            name='profile_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.profile'),
        ),
    ]
