# Generated by Django 4.1.6 on 2023-02-14 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_config_contact_alter_config_profile_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='config',
            old_name='profile_id',
            new_name='profile',
        ),
    ]
