# Generated by Django 4.1.6 on 2023-02-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_rename_profile_id_config_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='contact',
        ),
        migrations.AddField(
            model_name='config',
            name='contact',
            field=models.ManyToManyField(to='member.contact'),
        ),
    ]
