# Generated by Django 4.1.6 on 2023-02-14 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_remove_config_contact_config_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('1', 'sent'), ('0', 'receive')], max_length=1)),
                ('sent_date', models.DateTimeField(auto_now=True)),
                ('update_data', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='member.contact')),
            ],
        ),
    ]
