# Generated by Django 4.1.6 on 2023-02-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_otptimeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='otptimeline',
            name='provider',
            field=models.CharField(default='amazone', max_length=120),
            preserve_default=False,
        ),
    ]
